//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxyBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1037")]
        public int Width {
            get {
                return ((int)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("803")]
        public int Height {
            get {
                return ((int)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool collectchests {
            get {
                return ((bool)(this["collectchests"]));
            }
            set {
                this["collectchests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool collecteventchests {
            get {
                return ((bool)(this["collecteventchests"]));
            }
            set {
                this["collecteventchests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int collectorrange {
            get {
                return ((int)(this["collectorrange"]));
            }
            set {
                this["collectorrange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int repathp {
            get {
                return ((int)(this["repathp"]));
            }
            set {
                this["repathp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool repatcorner {
            get {
                return ((bool)(this["repatcorner"]));
            }
            set {
                this["repatcorner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoJoinRaid {
            get {
                return ((bool)(this["autoJoinRaid"]));
            }
            set {
                this["autoJoinRaid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ammoRaid {
            get {
                return ((string)(this["ammoRaid"]));
            }
            set {
                this["ammoRaid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CollectGlitters {
            get {
                return ((bool)(this["CollectGlitters"]));
            }
            set {
                this["CollectGlitters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShootMonsters {
            get {
                return ((bool)(this["ShootMonsters"]));
            }
            set {
                this["ShootMonsters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Monsters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Monsters"]));
            }
            set {
                this["Monsters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection NPCs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NPCs"]));
            }
            set {
                this["NPCs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool shootNPCs {
            get {
                return ((bool)(this["shootNPCs"]));
            }
            set {
                this["shootNPCs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool shootRaidBoss {
            get {
                return ((bool)(this["shootRaidBoss"]));
            }
            set {
                this["shootRaidBoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ammoRaidBoss {
            get {
                return ((string)(this["ammoRaidBoss"]));
            }
            set {
                this["ammoRaidBoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showLog {
            get {
                return ((bool)(this["showLog"]));
            }
            set {
                this["showLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoJoinBM {
            get {
                return ((bool)(this["autoJoinBM"]));
            }
            set {
                this["autoJoinBM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ammoBM {
            get {
                return ((string)(this["ammoBM"]));
            }
            set {
                this["ammoBM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool onlyFullHPNpcs {
            get {
                return ((bool)(this["onlyFullHPNpcs"]));
            }
            set {
                this["onlyFullHPNpcs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool onlyFullHPMonsters {
            get {
                return ((bool)(this["onlyFullHPMonsters"]));
            }
            set {
                this["onlyFullHPMonsters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool onlyFullHPRaidNpcs {
            get {
                return ((bool)(this["onlyFullHPRaidNpcs"]));
            }
            set {
                this["onlyFullHPRaidNpcs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rebuyAmmo {
            get {
                return ((bool)(this["rebuyAmmo"]));
            }
            set {
                this["rebuyAmmo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.000")]
        public string rebuyAmmoAmount {
            get {
                return ((string)(this["rebuyAmmoAmount"]));
            }
            set {
                this["rebuyAmmoAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ammoNPCs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ammoNPCs"]));
            }
            set {
                this["ammoNPCs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection harpoonMonsters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["harpoonMonsters"]));
            }
            set {
                this["harpoonMonsters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string rebuyAmmoType {
            get {
                return ((string)(this["rebuyAmmoType"]));
            }
            set {
                this["rebuyAmmoType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int shootBackType {
            get {
                return ((int)(this["shootBackType"]));
            }
            set {
                this["shootBackType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shootBackAmmo {
            get {
                return ((string)(this["shootBackAmmo"]));
            }
            set {
                this["shootBackAmmo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string rebuyHarpoonsType {
            get {
                return ((string)(this["rebuyHarpoonsType"]));
            }
            set {
                this["rebuyHarpoonsType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rebuyHarpoons {
            get {
                return ((bool)(this["rebuyHarpoons"]));
            }
            set {
                this["rebuyHarpoons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string rebuyHarpoonsAmount {
            get {
                return ((string)(this["rebuyHarpoonsAmount"]));
            }
            set {
                this["rebuyHarpoonsAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool collectMeat {
            get {
                return ((bool)(this["collectMeat"]));
            }
            set {
                this["collectMeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool jumpMaps {
            get {
                return ((bool)(this["jumpMaps"]));
            }
            set {
                this["jumpMaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usePowderRaid {
            get {
                return ((bool)(this["usePowderRaid"]));
            }
            set {
                this["usePowderRaid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usePlatesRaid {
            get {
                return ((bool)(this["usePlatesRaid"]));
            }
            set {
                this["usePlatesRaid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usePowderRaidBoss {
            get {
                return ((bool)(this["usePowderRaidBoss"]));
            }
            set {
                this["usePowderRaidBoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usePlatesRaidBoss {
            get {
                return ((bool)(this["usePlatesRaidBoss"]));
            }
            set {
                this["usePlatesRaidBoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usePowderBM {
            get {
                return ((bool)(this["usePowderBM"]));
            }
            set {
                this["usePowderBM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usePlatesBM {
            get {
                return ((bool)(this["usePlatesBM"]));
            }
            set {
                this["usePlatesBM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usePowderPlayer {
            get {
                return ((bool)(this["usePowderPlayer"]));
            }
            set {
                this["usePowderPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usePlatesPlayer {
            get {
                return ((bool)(this["usePlatesPlayer"]));
            }
            set {
                this["usePlatesPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool firstStart {
            get {
                return ((bool)(this["firstStart"]));
            }
            set {
                this["firstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string repDesign {
            get {
                return ((string)(this["repDesign"]));
            }
            set {
                this["repDesign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string botDesign {
            get {
                return ((string)(this["botDesign"]));
            }
            set {
                this["botDesign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useDesignChanger {
            get {
                return ((bool)(this["useDesignChanger"]));
            }
            set {
                this["useDesignChanger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int maxRaidRejoins {
            get {
                return ((int)(this["maxRaidRejoins"]));
            }
            set {
                this["maxRaidRejoins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useRaidBossCandle {
            get {
                return ((bool)(this["useRaidBossCandle"]));
            }
            set {
                this["useRaidBossCandle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useRaidBossSnowman {
            get {
                return ((bool)(this["useRaidBossSnowman"]));
            }
            set {
                this["useRaidBossSnowman"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useFleeSmoke {
            get {
                return ((bool)(this["useFleeSmoke"]));
            }
            set {
                this["useFleeSmoke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useFleeSpeed {
            get {
                return ((bool)(this["useFleeSpeed"]));
            }
            set {
                this["useFleeSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useShootbackHPItem {
            get {
                return ((bool)(this["useShootbackHPItem"]));
            }
            set {
                this["useShootbackHPItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useShootbackVPItem {
            get {
                return ((bool)(this["useShootbackVPItem"]));
            }
            set {
                this["useShootbackVPItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int shootbackHPItemID {
            get {
                return ((int)(this["shootbackHPItemID"]));
            }
            set {
                this["shootbackHPItemID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int shootbackVPItemID {
            get {
                return ((int)(this["shootbackVPItemID"]));
            }
            set {
                this["shootbackVPItemID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shootbackHPItem {
            get {
                return ((string)(this["shootbackHPItem"]));
            }
            set {
                this["shootbackHPItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shootbackVPItem {
            get {
                return ((string)(this["shootbackVPItem"]));
            }
            set {
                this["shootbackVPItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useSkyfire {
            get {
                return ((bool)(this["useSkyfire"]));
            }
            set {
                this["useSkyfire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useElmosfire {
            get {
                return ((bool)(this["useElmosfire"]));
            }
            set {
                this["useElmosfire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useHumanMovement {
            get {
                return ((bool)(this["useHumanMovement"]));
            }
            set {
                this["useHumanMovement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool collectCargo {
            get {
                return ((bool)(this["collectCargo"]));
            }
            set {
                this["collectCargo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool finishNPCs {
            get {
                return ((bool)(this["finishNPCs"]));
            }
            set {
                this["finishNPCs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool joinSameBonusMap {
            get {
                return ((bool)(this["joinSameBonusMap"]));
            }
            set {
                this["joinSameBonusMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool attackOnSight {
            get {
                return ((bool)(this["attackOnSight"]));
            }
            set {
                this["attackOnSight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection attackOnSightList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["attackOnSightList"]));
            }
            set {
                this["attackOnSightList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool repatborder {
            get {
                return ((bool)(this["repatborder"]));
            }
            set {
                this["repatborder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool jumpMapCircle {
            get {
                return ((bool)(this["jumpMapCircle"]));
            }
            set {
                this["jumpMapCircle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool jumpMapRandom {
            get {
                return ((bool)(this["jumpMapRandom"]));
            }
            set {
                this["jumpMapRandom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int jumpMapTimer {
            get {
                return ((int)(this["jumpMapTimer"]));
            }
            set {
                this["jumpMapTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClearCache {
            get {
                return ((bool)(this["ClearCache"]));
            }
            set {
                this["ClearCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int repAtHPRaid {
            get {
                return ((int)(this["repAtHPRaid"]));
            }
            set {
                this["repAtHPRaid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int repAtHPBM {
            get {
                return ((int)(this["repAtHPBM"]));
            }
            set {
                this["repAtHPBM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rangeBMNpcs {
            get {
                return ((bool)(this["rangeBMNpcs"]));
            }
            set {
                this["rangeBMNpcs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool jumpMapIfAvailable {
            get {
                return ((bool)(this["jumpMapIfAvailable"]));
            }
            set {
                this["jumpMapIfAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool fleeToIsland {
            get {
                return ((bool)(this["fleeToIsland"]));
            }
            set {
                this["fleeToIsland"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool repairAtIsland {
            get {
                return ((bool)(this["repairAtIsland"]));
            }
            set {
                this["repairAtIsland"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ignoreBoxesPlayerNearby {
            get {
                return ((bool)(this["ignoreBoxesPlayerNearby"]));
            }
            set {
                this["ignoreBoxesPlayerNearby"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection usernamesList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["usernamesList"]));
            }
            set {
                this["usernamesList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection passwordsList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["passwordsList"]));
            }
            set {
                this["passwordsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int finishNPCHpLimit {
            get {
                return ((int)(this["finishNPCHpLimit"]));
            }
            set {
                this["finishNPCHpLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rebuyRaidMedallions {
            get {
                return ((bool)(this["rebuyRaidMedallions"]));
            }
            set {
                this["rebuyRaidMedallions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string useActionItemID {
            get {
                return ((string)(this["useActionItemID"]));
            }
            set {
                this["useActionItemID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string useActionItemType {
            get {
                return ((string)(this["useActionItemType"]));
            }
            set {
                this["useActionItemType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useActionItemUser {
            get {
                return ((bool)(this["useActionItemUser"]));
            }
            set {
                this["useActionItemUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool boardVCMA {
            get {
                return ((bool)(this["boardVCMA"]));
            }
            set {
                this["boardVCMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fixed-Waypoints")]
        public string movementType {
            get {
                return ((string)(this["movementType"]));
            }
            set {
                this["movementType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool prioNPCs {
            get {
                return ((bool)(this["prioNPCs"]));
            }
            set {
                this["prioNPCs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool betterGFX {
            get {
                return ((bool)(this["betterGFX"]));
            }
            set {
                this["betterGFX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool avoidIslands {
            get {
                return ((bool)(this["avoidIslands"]));
            }
            set {
                this["avoidIslands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tasksDoneLogout {
            get {
                return ((bool)(this["tasksDoneLogout"]));
            }
            set {
                this["tasksDoneLogout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int rebuyAmooSmaller {
            get {
                return ((int)(this["rebuyAmooSmaller"]));
            }
            set {
                this["rebuyAmooSmaller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int rebuyHarpoonsSmaller {
            get {
                return ((int)(this["rebuyHarpoonsSmaller"]));
            }
            set {
                this["rebuyHarpoonsSmaller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool prioMonsters {
            get {
                return ((bool)(this["prioMonsters"]));
            }
            set {
                this["prioMonsters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool joinBeheLvl26 {
            get {
                return ((bool)(this["joinBeheLvl26"]));
            }
            set {
                this["joinBeheLvl26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool acceptLoginBonus {
            get {
                return ((bool)(this["acceptLoginBonus"]));
            }
            set {
                this["acceptLoginBonus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool collectWhileAttack {
            get {
                return ((bool)(this["collectWhileAttack"]));
            }
            set {
                this["collectWhileAttack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool avoidBeheNPCs {
            get {
                return ((bool)(this["avoidBeheNPCs"]));
            }
            set {
                this["avoidBeheNPCs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rebuyKeys {
            get {
                return ((bool)(this["rebuyKeys"]));
            }
            set {
                this["rebuyKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool fleeIfEnemyNearby {
            get {
                return ((bool)(this["fleeIfEnemyNearby"]));
            }
            set {
                this["fleeIfEnemyNearby"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string login_username {
            get {
                return ((string)(this["login_username"]));
            }
            set {
                this["login_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string login_password {
            get {
                return ((string)(this["login_password"]));
            }
            set {
                this["login_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useBMAmmoChanger {
            get {
                return ((bool)(this["useBMAmmoChanger"]));
            }
            set {
                this["useBMAmmoChanger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bmAmmoChanged {
            get {
                return ((string)(this["bmAmmoChanged"]));
            }
            set {
                this["bmAmmoChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int bmAmmoChangerWave {
            get {
                return ((int)(this["bmAmmoChangerWave"]));
            }
            set {
                this["bmAmmoChangerWave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useQuestSystem {
            get {
                return ((bool)(this["useQuestSystem"]));
            }
            set {
                this["useQuestSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool doDaily21Quest {
            get {
                return ((bool)(this["doDaily21Quest"]));
            }
            set {
                this["doDaily21Quest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection selectedQuests {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["selectedQuests"]));
            }
            set {
                this["selectedQuests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useRaidBossSpeedstone {
            get {
                return ((bool)(this["useRaidBossSpeedstone"]));
            }
            set {
                this["useRaidBossSpeedstone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useRaidBossBloodlust {
            get {
                return ((bool)(this["useRaidBossBloodlust"]));
            }
            set {
                this["useRaidBossBloodlust"] = value;
            }
        }
    }
}
